# Generated by Django 3.1.5 on 2021-01-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kyc_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_address', models.EmailField(help_text='Required. Inform a valid email address.', max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('date_of_birth', models.CharField(max_length=30)),
                ('Nationality', models.CharField(max_length=30)),
                ('address_line_1', models.CharField(max_length=30)),
                ('address_line_2', models.CharField(max_length=30)),
                ('city_of_residence', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=30)),
                ('telegram_username', models.CharField(max_length=30)),
            ],
        ),
    ]
