# Generated by Django 3.1.5 on 2021-01-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexfiat_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc_application',
            name='back_image',
            field=models.ImageField(null=True, upload_to='media/image'),
        ),
        migrations.AddField(
            model_name='kyc_application',
            name='front_image',
            field=models.ImageField(null=True, upload_to='media/image'),
        ),
        migrations.AddField(
            model_name='kyc_application',
            name='wallet',
            field=models.CharField(choices=[('eth', 'ETHEREUM'), ('btc', 'BITCOIN'), ('dac', 'DASHCOIN')], default='eth', max_length=20),
        ),
        migrations.AddField(
            model_name='kyc_application',
            name='wallet_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kyc_application',
            name='Nationality',
            field=models.CharField(choices=[('UK', 'United KingDom'), ('US', 'UNITED STATE'), ('france', 'FRANCE'), ('china', 'CHINA'), ('czech republic', 'Czech Republic'), ('columbia', 'COLOMBIA')], default='UK', max_length=20),
        ),
        migrations.AlterField(
            model_name='kyc_application',
            name='email_address',
            field=models.EmailField(help_text='Required. Inform a valid email address.', max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc_application',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kyc_application',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
