# Generated by Django 3.1.5 on 2021-01-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexfiat_user', '0002_auto_20210127_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_application',
            name='back_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='kyc_application',
            name='front_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
