# Generated by Django 3.1.5 on 2021-01-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dexfiat_user', '0007_auto_20210129_2336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
