# Generated by Django 3.1.5 on 2021-01-29 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dexfiat_user', '0009_auto_20210130_0021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
