# Generated by Django 3.1.5 on 2021-01-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexfiat_user', '0013_auto_20210130_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
