# Generated by Django 3.1.5 on 2021-01-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexfiat_user', '0014_profile_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_application',
            name='email_address',
            field=models.EmailField(max_length=50),
        ),
    ]
